/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Wed Nov 24 09:25:16 CST 2004 by MyEclipse Hibernate Tool.
 */
package com.aof.component.helpdesk;

import java.io.Serializable;
import java.util.List;

/**
 * A class that represents a row in the CustConfigTableType table. 
 * You can customize the behavior of this class by editing the class, {@link CustConfigTableType()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCustConfigTableType 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the simple name property. */
    private java.lang.String name;

    /** The value of the simple disabled property. */
    private Boolean disabled;

    private ModifyLog modifyLog=new ModifyLog();
    
    private List columns;

    /**
     * Simple constructor of AbstractCustConfigTableType instances.
     */
    public AbstractCustConfigTableType()
    {
    }

    /**
     * Constructor of AbstractCustConfigTableType instances given a simple primary key.
     * @param id
     */
    public AbstractCustConfigTableType(java.lang.Integer typeId)
    {
        this.setId(typeId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Integer typeId)
    {
        this.hashValue = 0;
        this.id = typeId;
    }

    /**
     * Return the value of the type_name column.
     * @return java.lang.String
     */
    public java.lang.String getName()
    {
        return this.name;
    }

    /**
     * Set the value of the type_name column.
     * @param name
     */
    public void setName(java.lang.String typeName)
    {
        this.name = typeName;
    }

    /**
     * Return the value of the disabled column.
     * @return java.lang.Byte
     */
    public Boolean getDisabled()
    {
        return this.disabled;
    }

    /**
     * Set the value of the disabled column.
     * @param disabled
     */
    public void setDisabled(Boolean disabled)
    {
        this.disabled = disabled;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof CustConfigTableType))
            return false;
        CustConfigTableType that = (CustConfigTableType) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int typeIdValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + typeIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
    
    
	/**
	 * @return Returns the columns.
	 */
	public List getColumns() {
		return columns;
	}
	/**
	 * @param columns The columns to set.
	 */
	public void setColumns(List columns) {
		this.columns = columns;
	}
	/**
	 * @return Returns the modifyLog.
	 */
	public ModifyLog getModifyLog() {
		return modifyLog;
	}
	/**
	 * @param modifyLog The modifyLog to set.
	 */
	public void setModifyLog(ModifyLog modifyLog) {
		this.modifyLog = modifyLog;
	}
}
