/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 22 09:26:50 CST 2004 by MyEclipse Hibernate Tool.
 */
package com.aof.component.helpdesk;

import java.io.Serializable;
import java.util.Set;

import com.aof.component.domain.party.Party;

/**
 * A class that represents a row in the custConfigTable table. 
 * You can customize the behavior of this class by editing the class, {@link CustConfigTable()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCustConfigTable 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the company association. */
    private Party company;

    /** The value of the simple name property. */
    //private java.lang.String name;
    
    private CustConfigTableType tableType;
    
    //private String description;
    //private Set columns;

    /**
     * Simple constructor of AbstractCustConfigTable instances.
     */
    public AbstractCustConfigTable()
    {
    }

    /**
     * Constructor of AbstractCustConfigTable instances given a simple primary key.
     * @param id
     */
    public AbstractCustConfigTable(java.lang.Integer tableId)
    {
        this.setId(tableId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Integer tableId)
    {
        this.hashValue = 0;
        this.id = tableId;
    }

    /**
     * Return the value of the cust_id column.
     * @return Party
     */
    public Party getCompany()
    {
        return this.company;
    }

    /**
     * Set the value of the cust_id column.
     * @param company
     */
    public void setCompany(Party party)
    {
        this.company = party;
    }

    /**
     * Return the value of the table_name column.
     * @return java.lang.String
     */
   /* public java.lang.String getName()
    {
        return this.name;
    }*/

    /**
     * Set the value of the table_name column.
     * @param name
     */
    /*public void setName(java.lang.String tableName)
    {
        this.name = tableName;
    }*/

    
	/**
	 * @return Returns the columns.
	 */
	/*public Set getColumns() {
		return columns;
	}*/
	/**
	 * @param columns The columns to set.
	 */
	/*public void setColumns(Set columns) {
		this.columns = columns;
	}*/
    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof CustConfigTable))
            return false;
        CustConfigTable that = (CustConfigTable) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int tableIdValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + tableIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
	/**
	 * @return Returns the tableType.
	 */
	public CustConfigTableType getTableType() {
		return tableType;
	}
	/**
	 * @param tableType The tableType to set.
	 */
	public void setTableType(CustConfigTableType tableType) {
		this.tableType = tableType;
	}
	
	

}
