/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 22 09:26:50 CST 2004 by MyEclipse Hibernate Tool.
 */
package com.aof.component.helpdesk;

import java.io.Serializable;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * A class that represents a row in the custConfigRow table. 
 * You can customize the behavior of this class by editing the class, {@link CustConfigRow()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCustConfigRow 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the table association. */
    private CustConfigTable table;
    
    private Map items=new HashMap();

    /**
     * Simple constructor of AbstractCustConfigRow instances.
     */
    public AbstractCustConfigRow()
    {
    }

    /**
     * Constructor of AbstractCustConfigRow instances given a simple primary key.
     * @param id
     */
    public AbstractCustConfigRow(java.lang.Integer rowId)
    {
        this.setId(rowId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param id
     */
    public void setId(java.lang.Integer rowId)
    {
        this.hashValue = 0;
        this.id = rowId;
    }

    /**
     * Return the value of the table_id column.
     * @return CustConfigTable
     */
    public CustConfigTable getTable()
    {
        return this.table;
    }

    /**
     * Set the value of the table_id column.
     * @param table
     */
    public void setTable(CustConfigTable custconfigtable)
    {
        this.table = custconfigtable;
    }

    
	/**
	 * @return Returns the items.
	 */
	public Map getItems() {
		return items;
	}
	/**
	 * @param items The items to set.
	 */
	public void setItems(Map items) {
		this.items = items;
	}
    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof CustConfigRow))
            return false;
        CustConfigRow that = (CustConfigRow) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int rowIdValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + rowIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
