/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Nov 12 12:04:39 CST 2004 by MyEclipse Hibernate Tool.
 */
package com.aof.component.helpdesk;

import com.aof.component.domain.party.*;
import java.io.Serializable;

/**
 * A class that represents a row in the CM_Status_History table. 
 * You can customize the behavior of this class by editing the class, {@link CallStatusHistory()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCallStatusHistory 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer Id;


    private CallActionHistory callActionHistory;
   
    /** The value of the simple StatusOld property. */
    private StatusType statusOld;

    /** The value of the simple StatusNew property. */
    private StatusType statusNew;

    /** The value of the simple Desc property. */
    private java.lang.String desc;

    private ModifyLog modifyLog=new ModifyLog();
    
    /**
     * Simple constructor of AbstractCallStatusHistory instances.
     */
    public AbstractCallStatusHistory()
    {
    }

    /**
     * Constructor of AbstractCallStatusHistory instances given a simple primary key.
     * @param Id
     */
    public AbstractCallStatusHistory(java.lang.Integer Id)
    {
        this.setId(Id);
    }

    
    public CallActionHistory getCallActionHistory()
    {
    	return callActionHistory;
    	
    }
    
    public void setCallActionHistory(CallActionHistory callActionHistory)
    {
    	this.callActionHistory=callActionHistory;
    	
    }
    
    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return Id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param Id
     */
    public void setId(java.lang.Integer Id)
    {
        this.hashValue = 0;
        this.Id = Id;
    }

   
    /**
     * Return the value of the _Status_Old column.
     * @return java.lang.String
     */
    public StatusType getStatusOld()
    {
        return this.statusOld;
    }

    /**
     * Set the value of the _Status_Old column.
     * @param StatusOld
     */
    public void setStatusOld(StatusType StatusOld)
    {
        this.statusOld = StatusOld;
    }

    /**
     * Return the value of the _Status_New column.
     * @return java.lang.String
     */
    public StatusType getStatusNew()
    {
        return this.statusNew;
    }

    /**
     * Set the value of the _Status_New column.
     * @param StatusNew
     */
    public void setStatusNew(StatusType StatusNew)
    {
        this.statusNew = StatusNew;
    }

    /**
     * Return the value of the _Desc column.
     * @return java.lang.String
     */
    public java.lang.String getDesc()
    {
        return this.desc;
    }

    /**
     * Set the value of the _Desc column.
     * @param Desc
     */
    public void setDesc(java.lang.String Desc)
    {
        this.desc = Desc;
    }

  	/**
  	 * @return Returns the modifyLog.
  	 */
  	public ModifyLog getModifyLog() {
  		return modifyLog;
  	}
  	/**
  	 * @param modifyLog The modifyLog to set.
  	 */
  	public void setModifyLog(ModifyLog modifyLog) {
  		this.modifyLog = modifyLog;
  	}
  	

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof CallStatusHistory))
            return false;
        CallStatusHistory that = (CallStatusHistory) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int IdValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + IdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
