/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Sat Nov 13 13:09:55 CST 2004 by MyEclipse Hibernate Tool.
 */
package com.aof.component.helpdesk;

import java.io.Serializable;

/**
 * A class that represents a row in the ACTION_TYPE table. 
 * You can customize the behavior of this class by editing the class, {@link ActionType()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractActionType 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer actionid;

    /** The value of the simple actiondesc property. */
    private java.lang.String actiondesc;

    private boolean actiondisabled;

    /** The value of the callType association. */
    private CallType callType;
    
    /**
     * Simple constructor of AbstractActionType instances.
     */
    public AbstractActionType()
    {
    }

    /**
     * Constructor of AbstractActionType instances given a simple primary key.
     * @param actionid
     */
    public AbstractActionType(java.lang.Integer actionid)
    {
        this.setActionid(actionid);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getActionid()
    {
        return actionid;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param actionid
     */
    public void setActionid(java.lang.Integer actionid)
    {
        this.hashValue = 0;
        this.actionid = actionid;
    }

    /**
     * Return the value of the ActionDesc column.
     * @return java.lang.String
     */
    public java.lang.String getActiondesc()
    {
        return this.actiondesc;
    }

    /**
     * Set the value of the ActionDesc column.
     * @param actiondesc
     */
    public void setActiondesc(java.lang.String actiondesc)
    {
        this.actiondesc = actiondesc;
    }

    public boolean getActiondisabled() {
        return actiondisabled;
    }
    
    public void setActiondisabled(boolean actiondisabled) {
        this.actiondisabled = actiondisabled;
    }
    
    /**
     * Return the value of the status_type column.
     * @return CallType
     */
    public CallType getCallType()
    {
        return this.callType;
    }

    /**
     * Set the value of the status_type column.
     * @param callType
     */
    public void setCallType(CallType callType)
    {
        this.callType = callType;
    }
    
    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof ActionType))
            return false;
        ActionType that = (ActionType) rhs;
        if (this.getActionid() != null && that.getActionid() != null)
        {
            if (! this.getActionid().equals(that.getActionid()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int actionidValue = this.getActionid() == null ? 0 : this.getActionid().hashCode();
            result = result * 37 + actionidValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
