/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Fri Nov 12 12:04:39 CST 2004 by MyEclipse Hibernate Tool.
 */
package com.aof.component.helpdesk;

import java.io.Serializable;

import com.aof.component.domain.party.*;
import com.aof.component.helpdesk.servicelevel.*;
/**
 * A class that represents a row in the Call_Master table. 
 * You can customize the behavior of this class by editing the class, {@link CallMaster()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCallMaster 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer callID;

    /** The value of the company association. */
    private Party company=new Party();

    /** The value of the contact association. */
    private UserLogin contact=new UserLogin();

    /** The value of the simple type property. */
    private CallType type;

    /** The value of the simple type2 property. */
    private java.lang.String type2;

    /** The value of the simple requestType property. */
    private SLACategory requestType;

    /** The value of the simple priority property. */
    private SLAPriority priority=new SLAPriority();

    /** The value of the simple subject property. */
    private java.lang.String subject;

    /** The value of the simple Desc property. */
    private java.lang.String desc;

    /** The value of the simple Status property. */
    private StatusType status;

    /** The value of the simple AcceptedDate property. */
    private java.util.Date acceptedDate;

    /** The value of the simple TargetDate property. */
    private java.util.Date targetResponseDate;

    /** The value of the simple SolvedDate property. */
    private java.util.Date targetSolvedDate;

    /** The value of the simple ClosedDate property. */
    private java.util.Date targetClosedDate;
    
    private java.util.Date responseDate;
    
    private java.util.Date solvedDate;
    
    private java.util.Date closedDate;
    
    private java.lang.String ticketNo;
    
	private java.lang.String escalated;
	private java.lang.String reAssigned;
    
    private UserLogin  solveUser=null;
    
    private RequestType requestType2;
    
    private ProblemType problemType;
    
    private float sumCost=0;
    

    /** The value of the simple attachmentid property. */
    private java.lang.String attachGroupID;


    private ModifyLog modifyLog=new ModifyLog();
    
    private ContactInfo contactInfo=new ContactInfo();
    /*
     <many-to-one name="assignedParty" column="CM_Assigned_Party" class="com.aof.component.domain.party.Party" />
     <many-to-one name="assignedUser" column="CM_Assigned_User" class="com.aof.component.domain.party.UserLogin" />     
     */
    private UserLogin  assignedUser=new UserLogin();
    
    private Party assignedParty=new Party();

    
	private java.lang.String notifyCustomer;
    
    
	/**
	 * @return Returns the assignedParty.
	 */
	public Party getAssignedParty() {
		return assignedParty;
	}
	/**
	 * @param assignedParty The assignedParty to set.
	 */
	public void setAssignedParty(Party assignedParty) {
		this.assignedParty = assignedParty;
	}
	/**
	 * @return Returns the assignedUser.
	 */
	public UserLogin getAssignedUser() {
		return assignedUser;
	}
	/**
	 * @param assignedUser The assignedUser to set.
	 */
	public void setAssignedUser(UserLogin assignedUser) {
		this.assignedUser = assignedUser;
	}
	/**
	 * @return Returns the acceptedDate.
	 */
	public java.util.Date getAcceptedDate() {
		return acceptedDate;
	}
	/**
	 * @param acceptedDate The acceptedDate to set.
	 */
	public void setAcceptedDate(java.util.Date acceptedDate) {
		this.acceptedDate = acceptedDate;
	}
	/**
	 * @return Returns the attachGroupID.
	 */
	public java.lang.String getAttachGroupID() {
		return attachGroupID;
	}
	/**
	 * @param attachGroupID The attachGroupID to set.
	 */
	public void setAttachGroupID(java.lang.String attachmentID) {
		this.attachGroupID = attachmentID;
	}
	/**
	 * @return Returns the callID.
	 */
	public java.lang.Integer getCallID() {
		return callID;
	}
	/**
	 * @param callID The callID to set.
	 */
	public void setCallID(java.lang.Integer callID) {
		this.callID = callID;
	}
	/**
	 * @return Returns the company.
	 */
	public Party getCompany() {
		return company;
	}
	/**
	 * @param company The company to set.
	 */
	public void setCompany(Party company) {
		this.company = company;
	}
	/**
	 * @return Returns the contact.
	 */
	public UserLogin getContact() {
		return contact;
	}
	/**
	 * @param contact The contact to set.
	 */
	public void setContact(UserLogin contact) {
		this.contact = contact;
	}
	/**
	 * @return Returns the contactInfo.
	 */
	public ContactInfo getContactInfo() {
		return contactInfo;
	}
	/**
	 * @param contactInfo The contactInfo to set.
	 */
	public void setContactInfo(ContactInfo contactInfo) {
		this.contactInfo = contactInfo;
	}
	/**
	 * @return Returns the desc.
	 */
	public java.lang.String getDesc() {
		return desc;
	}
	/**
	 * @param desc The desc to set.
	 */
	public void setDesc(java.lang.String desc) {
		this.desc = desc;
	}
	
	/**
	 * @return Returns the modifyLog.
	 */
	public ModifyLog getModifyLog() {
		return modifyLog;
	}
	/**
	 * @param modifyLog The modifyLog to set.
	 */
	public void setModifyLog(ModifyLog modifyLog) {
		this.modifyLog = modifyLog;
	}
	/**
	 * @return Returns the priority.
	 */
	public SLAPriority getPriority() {
		return priority;
	}
	/**
	 * @param priority The priority to set.
	 */
	public void setPriority(SLAPriority priority) {
		this.priority = priority;
	}
	/**
	 * @return Returns the requestType.
	 */
	public SLACategory getRequestType() {
		return requestType;
	}
	/**
	 * @param requestType The requestType to set.
	 */
	public void setRequestType(SLACategory requestType) {
		this.requestType = requestType;
	}
	/**
	 * @return Returns the status.
	 */
	public StatusType getStatus() {
		return status;
	}
	/**
	 * @param status The status to set.
	 */
	public void setStatus(StatusType status) {
		this.status = status;
	}
	/**
	 * @return Returns the subject.
	 */
	public java.lang.String getSubject() {
		return subject;
	}
	/**
	 * @param subject The subject to set.
	 */
	public void setSubject(java.lang.String subject) {
		this.subject = subject;
	}
	/**
	 * @return Returns the targetClosedDate.
	 */
	public java.util.Date getTargetClosedDate() {
		return targetClosedDate;
	}
	/**
	 * @param targetClosedDate The targetClosedDate to set.
	 */
	public void setTargetClosedDate(java.util.Date targetClosedDate) {
		this.targetClosedDate = targetClosedDate;
	}
	/**
	 * @return Returns the targetResponseDate.
	 */
	public java.util.Date getTargetResponseDate() {
		return targetResponseDate;
	}
	/**
	 * @param targetResponseDate The targetResponseDate to set.
	 */
	public void setTargetResponseDate(java.util.Date targetResponseDate) {
		this.targetResponseDate = targetResponseDate;
	}
	/**
	 * @return Returns the targetSolvedDate.
	 */
	public java.util.Date getTargetSolvedDate() {
		return targetSolvedDate;
	}
	/**
	 * @param targetSolvedDate The targetSolvedDate to set.
	 */
	public void setTargetSolvedDate(java.util.Date targetSolvedDate) {
		this.targetSolvedDate = targetSolvedDate;
	}
	/**
	 * @return Returns the type.
	 */
	public CallType getType() {
		return type;
	}
	/**
	 * @param type The type to set.
	 */
	public void setType(CallType type) {
		this.type = type;
	}
	/**
	 * @return Returns the type2.
	 */
	public java.lang.String getType2() {
		return type2;
	}
	/**
	 * @param type2 The type2 to set.
	 */
	public void setType2(java.lang.String type2) {
		this.type2 = type2;
	}
	
	
	
	
	/**
	 * @return Returns the closedDate.
	 */
	public java.util.Date getClosedDate() {
		return closedDate;
	}
	/**
	 * @param closedDate The closedDate to set.
	 */
	public void setClosedDate(java.util.Date closedDate) {
		this.closedDate = closedDate;
	}
	/**
	 * @return Returns the responseDate.
	 */
	public java.util.Date getResponseDate() {
		return responseDate;
	}
	/**
	 * @param responseDate The responseDate to set.
	 */
	public void setResponseDate(java.util.Date responseDate) {
		this.responseDate = responseDate;
	}
	/**
	 * @return Returns the solvedDate.
	 */
	public java.util.Date getSolvedDate() {
		return solvedDate;
	}
	/**
	 * @param solvedDate The solvedDate to set.
	 */
	public void setSolvedDate(java.util.Date solvedDate) {
		this.solvedDate = solvedDate;
	}
	/**
	 * @return Returns the solveUser.
	 */
	public UserLogin getSolveUser() {
		return solveUser;
	}
	/**
	 * @param solveUser The solveUser to set.
	 */
	public void setSolveUser(UserLogin solveUser) {
		this.solveUser = solveUser;
	}
	/**
	 * @return Returns the sumCost.
	 */
	public float getSumCost() {
		return sumCost;
	}
	/**
	 * @param sumCost The sumCost to set.
	 */
	public void setSumCost(float sumCost) {
		this.sumCost = sumCost;
	}
	
	
	
	
	
	
	
	
	
	/**
	 * @return Returns the ticketNo.
	 */
	public java.lang.String getTicketNo() {
		return ticketNo;
	}
	/**
	 * @param ticketNo The ticketNo to set.
	 */
	public void setTicketNo(java.lang.String ticketNo) {
		this.ticketNo = ticketNo;
	}
	
	
	
	/**
	 * @return Returns the requestType2.
	 */
	public RequestType getRequestType2() {
		return requestType2;
	}
	/**
	 * @param requestType2 The requestType2 to set.
	 */
	public void setRequestType2(RequestType requestType2) {
		this.requestType2 = requestType2;
	}
    /**
     * Simple constructor of AbstractCallMaster instances.
     */
    public AbstractCallMaster()
    {
    }

    /**
     * Constructor of AbstractCallMaster instances given a simple primary key.
     * @param callID
     */
    public AbstractCallMaster(java.lang.Integer Id)
    {
        this.setCallID(Id);
    }
    
    

   

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof CallMaster))
            return false;
        CallMaster that = (CallMaster) rhs;
        if (this.getCallID() != null && that.getCallID() != null)
        {
            if (! this.getCallID().equals(that.getCallID()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int IdValue = this.getCallID() == null ? 0 : this.getCallID().hashCode();
            result = result * 37 + IdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
    
	/**
	 * @return
	 */
	public ProblemType getProblemType() {
		return problemType;
	}

	/**
	 * @param type
	 */
	public void setProblemType(ProblemType type) {
		problemType = type;
	}
	
	/**
	 * @return
	 */
	public java.lang.String getNotifyCustomer() {
		return this.notifyCustomer;
	}
	/**
	 * @param type
	 */
	public void setNotifyCustomer(java.lang.String type) {
		this.notifyCustomer = type;
	}
	
	public java.lang.String getReAssigned() {
		return this.reAssigned;
	}
	public void setReAssigned(java.lang.String type) {
		this.reAssigned = type;
	}
	public java.lang.String getEscalated() {
		return this.escalated;
	}
	public void setEscalated(java.lang.String type) {
		this.escalated = type;
	}
}
