/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Thu Dec 02 15:56:57 CST 2004 by MyEclipse Hibernate Tool.
 */
package com.aof.component.helpdesk;

import java.io.Serializable;

/**
 * A class that represents a row in the Status_Type table. 
 * You can customize the behavior of this class by editing the class, {@link StatusType()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractStatusType 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The composite primary key value. */
    private java.lang.Integer id;

    /** The value of the callType association. */
    private CallType callType;

    /** The value of the simple statusLevel property. */
    private java.lang.Integer level;

    /** The value of the simple statusDisabled property. */
    private java.lang.Boolean disabled;

    /** The value of the simple statusDesc property. */
    private java.lang.String desc;
    
	
    private java.lang.Integer flag=new Integer(0);

    /**
     * Simple constructor of AbstractStatusType instances.
     */
    public AbstractStatusType()
    {
    }

    /**
     * Constructor of AbstractStatusType instances given a simple primary key.
     * @param stutusId
     */
    public AbstractStatusType(java.lang.Integer stutusId)
    {
        this.setId(stutusId);
    }

    /**
     * Return the simple primary key value that identifies this object.
     * @return java.lang.Integer
     */
    public java.lang.Integer getId()
    {
        return id;
    }

    /**
     * Set the simple primary key value that identifies this object.
     * @param stutusId
     */
    public void setId(java.lang.Integer stutusId)
    {
        this.hashValue = 0;
        this.id = stutusId;
    }

    /**
  	 * @return Returns the flag.
  	 */
  	public java.lang.Integer getFlag() {
  		return flag;
  	}
  	/**
  	 * @param flag The flag to set.
  	 */
  	public void setFlag(java.lang.Integer flag) {
  		this.flag = flag;
  	}
  	
    /**
     * Return the value of the status_type column.
     * @return CallType
     */
    public CallType getCallType()
    {
        return this.callType;
    }

    /**
     * Set the value of the status_type column.
     * @param callType
     */
    public void setCallType(CallType callType)
    {
        this.callType = callType;
    }

    /**
     * Return the value of the status_level column.
     * @return java.lang.Integer
     */
    public java.lang.Integer getLevel()
    {
        return this.level;
    }

    /**
     * Set the value of the status_level column.
     * @param statusLevel
     */
    public void setLevel(java.lang.Integer statusLevel)
    {
        this.level = statusLevel;
    }

    /**
     * Return the value of the status_disabled column.
     * @return java.lang.Byte
     */
    public java.lang.Boolean getDisabled()
    {
        return this.disabled;
    }

    /**
     * Set the value of the status_disabled column.
     * @param statusDisabled
     */
    public void setDisabled(java.lang.Boolean statusDisabled)
    {
        this.disabled = statusDisabled;
    }

    /**
     * Return the value of the status_desc column.
     * @return java.lang.String
     */
    public java.lang.String getDesc()
    {
        return this.desc;
    }

    /**
     * Set the value of the status_desc column.
     * @param statusDesc
     */
    public void setDesc(java.lang.String statusDesc)
    {
        this.desc = statusDesc;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof StatusType))
            return false;
        StatusType that = (StatusType) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            if (! this.getId().equals(that.getId()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int stutusIdValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + stutusIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
