/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 22 09:26:50 CST 2004 by MyEclipse Hibernate Tool.
 */
package com.aof.component.helpdesk;

import java.io.Serializable;

/**
 * A class that represents a row in the custConfigItem table. 
 * You can customize the behavior of this class by editing the class, {@link CustConfigItem()}.
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized * by MyEclipse Hibernate tool integration.
 */
public abstract class AbstractCustConfigItem 
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private int hashValue = 0;

    /** The simple primary key value. */
    private Integer id;

    /** The value of the simple content property. */
    private java.lang.String content;
    
    private CustConfigRow row;
    
    private CustConfigColumn column;
    /**
     * Simple constructor of AbstractCustConfigItem instances.
     */
    public AbstractCustConfigItem()
    {
    }

    /**
     * Constructor of AbstractCustConfigItem instances given a composite primary key.
     * @param id
     */
    public AbstractCustConfigItem(Integer id)
    {
        this.setId(id);
    }

    
    
    
	/**
	 * @return Returns the column.
	 */
	public CustConfigColumn getColumn() {
		return column;
	}
	/**
	 * @param column The column to set.
	 */
	public void setColumn(CustConfigColumn column) {
		this.column = column;
	}
	/**
	 * @return Returns the row.
	 */
	public CustConfigRow getRow() {
		return row;
	}
	/**
	 * @param row The row to set.
	 */
	public void setRow(CustConfigRow row) {
		this.row = row;
	}
    /**
     * Return the composite id instance that identifies this object.
     * @return CustConfigItemKey
     */
    public Integer getId()
    {
        return this.id;
    }

    /**
     * Set the composite id instance that identifies this object.
     * @param id
     */
    public void setId(Integer id)
    {
        this.hashValue = 0;
        this.id = id;
    }
    
    public Integer getColumnid() {
    	return this.getColumn().getId();
    }
    
    public void setColumnid(Integer columnId) {
    	this.getColumn().setId(columnId);
    }
    
    /**
     * Return the value of the content column.
     * @return java.lang.String
     */
    public java.lang.String getContent()
    {
        return this.content;
    }

    /**
     * Set the value of the content column.
     * @param content
     */
    public void setContent(java.lang.String content)
    {
        this.content = content;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the primary key values.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof CustConfigItem))
            return false;
        CustConfigItem that = (CustConfigItem) rhs;
        if (this.getId() != null && that.getId() != null)
        {
            return (this.getId().equals(that.getId()));
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int rowIdValue = this.getId() == null ? 0 : this.getId().hashCode();
            result = result * 37 + rowIdValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
