/*
 * WARNING: DO NOT EDIT THIS FILE. This is a generated file that is synchronized
 * by MyEclipse Hibernate tool integration.
 *
 * Created Mon Nov 22 09:26:50 CST 2004 by MyEclipse Hibernate Tool.
 */
package com.aof.component.helpdesk;

import java.io.Serializable;

/**
 * A class representing a composite primary key id for the custConfigItem
 * table.  This object should only be instantiated for use with instances 
 * of the CustConfigItem class.
 */
public class CustConfigItemKey
    implements Serializable
{
    /** The cached hash code value for this instance.  Settting to 0 triggers re-calculation. */
    private volatile int hashValue = 0;

    /** The value of the column_id component of this composite id. */
    private CustConfigColumn column;

    /** The value of the row_id component of this composite id. */
    private CustConfigRow row;

    /**
     * Simple constructor of CustConfigItemKey instances.
     */
    public CustConfigItemKey()
    {
    }
    
    

	/**
	 * @param column
	 * @param row
	 */
	public CustConfigItemKey(CustConfigColumn column, CustConfigRow row) {
		super();
		this.column = column;
		this.row = row;
	}
    /**
     * Returns the value of the column property.
     * @return CustConfigColumn
     */
    public CustConfigColumn getColumn()
    {
        return column;
    }

    /**
     * Sets the value of the column property.
     * @param column
     */
    public void setColumn(CustConfigColumn custconfigcolumn)
    {
        hashValue = 0;
        this.column = custconfigcolumn;
    }

    /**
     * Returns the value of the row property.
     * @return CustConfigRow
     */
    public CustConfigRow getRow()
    {
        return row;
    }

    /**
     * Sets the value of the row property.
     * @param row
     */
    public void setRow(CustConfigRow custconfigrow)
    {
        hashValue = 0;
        this.row = custconfigrow;
    }

    /**
     * Implementation of the equals comparison on the basis of equality of the id components.
     * @param rhs
     * @return boolean
     */
    public boolean equals(Object rhs)
    {
        if (rhs == null)
            return false;
        if (! (rhs instanceof CustConfigItemKey))
            return false;
        CustConfigItemKey that = (CustConfigItemKey) rhs;
        if (this.getColumn() != null && that.getColumn() != null)
        {
            if (! this.getColumn().equals(that.getColumn()))
            {
                return false;
            }
        }
        if (this.getRow() != null && that.getRow() != null)
        {
            if (! this.getRow().equals(that.getRow()))
            {
                return false;
            }
        }
        return true;
    }

    /**
     * Implementation of the hashCode method conforming to the Bloch pattern with
     * the exception of array properties (these are very unlikely primary key types).
     * @return int
     */
    public int hashCode()
    {
        if (this.hashValue == 0)
        {
            int result = 17;
            int custconfigcolumnValue = this.getColumn() == null ? 0 : this.getColumn().hashCode();
            result = result * 37 + custconfigcolumnValue;
            int custconfigrowValue = this.getRow() == null ? 0 : this.getRow().hashCode();
            result = result * 37 + custconfigrowValue;
            this.hashValue = result;
        }
        return this.hashValue;
    }
}
